### ISSUE TITLE
move in a loop?

### ISSUE THREAD

**Issue by arBmind** [elbeno/testinator#4]
Hey,

https://github.com/elbeno/testinator/blob/89fe6d3917bc4d074e8e01064aec3b83e7ccd9e2/src/include/function_traits.h#L51

it seems you are moving in a loop. I guess this is not valid.

**Comment by elbeno** [comment]
Thanks! You're right. Fixed with https://github.com/elbeno/testinator/commit/b4c1b92492c96f6c963263a26fc465fb83fcce03
